apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::997155076510:user/itaid-github-cd
      username: itaid-github-cd
      groups:
    - system:masters
